export { ApiKeyAuthProvider } from "./auth/api-key.ts";
export { OAuthAuthProvider } from "./auth/oauth.ts";
export type { AuthProvider } from "./auth/types.ts";
export type { TailscaleClientOptions } from "./client.ts";
export { TailscaleClient } from "./client.ts";
export { TailscaleApiError, TailscaleError } from "./errors.ts";

export type {
	ACLAutoApprovers,
	ACLEntry,
	ACLSSHRule,
	ACLTest,
	AutoApprovers,
	ClientConnectivity,
	ClientSupports,
	CreateKeyRequest,
	CreateServiceRequest,
	CreateWebhookRequest,
	DERPRegion,
	Device,
	DeviceRoutes,
	Distro,
	DNSNameservers,
	DNSPreferences,
	DNSSearchPaths,
	ISODateString,
	Key,
	KeyCapabilities,
	NodeAttrGrant,
	PolicyFile,
	PolicyGetResponse,
	PolicyRawResponse,
	Service,
	ServiceBackendHost,
	ServiceEndpoint,
	ServiceProtocol,
	ServiceResource,
	SetDeviceKeyRequest,
	SplitDNSConfig,
	TailnetInfo,
	TailnetMembership,
	TailnetSettings,
	TailnetUser,
	UpdateServiceRequest,
	UpdateWebhookRequest,
	User,
	UserGetResponse,
	UsersListResponse,
	Webhook,
	WebhookEvent,
	WebhookProviderType,
	WebhookSubscriptionType,
} from "./types/index.ts";
